language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
    - 2.5.5
    - 2.6.3
    - 2.7
services:
  - mongodb
env:
  - "RAILS_VERSION=6.1.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.0.0"
matrix:
  fast_finish: true
